import re
file_yaml = open('table2.yaml', 'w')
f = open('table.json')
g = f.readline()
file = f.read()
data = re.split(r'\{', file)
data = re.split(r'}', file)
print(data)
for i in range(len(data)):
    data[i] = re.sub(r'','',data[i])
    data[i] = re.sub(r',','',data[i])
    data[i] = re.sub(r'\{','',data[i])
    data[i] = re.sub(r'}','',data[i])
    data[i] = re.sub(r'\[','',data[i])
    data[i] = re.sub(r']','',data[i])
    data[i] = re.sub(r'"2"',"- '2'",data[i])
    data[i] = re.sub(r'"4"',"- '4'",data[i])
    data[i] = re.sub(r'"4"',"- '4'",data[i])
    data[i] = re.sub(r'"6"',"- '6'",data[i])
    data[i] = re.sub(r'"8"',"- '8'",data[i])
    data[i] = re.sub(r'"10"',"- '10'",data[i])
    data[i] = re.sub(r'"12"',"- '12'",data[i])
    data[i] = re.sub(r'"14"',"- '14'",data[i])
    data[i] = re.sub(r'"1"',"- '1'",data[i])
    data[i] = re.sub(r'"3"',"- '3'",data[i])
    data[i] = re.sub(r'"5"',"- '5'",data[i])
    data[i] = re.sub(r'"7"',"- '7'",data[i])
    data[i] = re.sub(r'"9"',"- '9'",data[i])
    data[i] = re.sub(r'"11"',"- '11'",data[i])
    data[i] = re.sub(r'"13"',"- '13'",data[i])
    data[i] = re.sub(r'"15"',"- '15'",data[i])
    data[i] = re.sub(r'"17"',"- '17'",data[i])
    data[i] = re.sub(r'"', '',data[i])
    if len(data[i]) > 0:
        file_yaml.write(data[i] + '\n')
file_yaml.close()

f = open('table1.yaml')
g = f.readline()
file = f.read()
file = file.replace('       ','   ')
file_yaml = open('table_yaml_2.yaml', 'w')
file_yaml.write('timetable:\n')
file_yaml.write(file)
